baseurl: /srkrishna.github.io

# Site Settings
title: radha krishnan
description:
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img:

exclude: ["Rakefile"]

theme: jekyll-theme-cayman